import { CommandCatalogItem } from '../models/command-catalog.models';

export const LOCAL_COMMAND_CATALOG: CommandCatalogItem[] = [
  {
    id: 'local-celem-bank-balance',
    projectSlug: 'celem-bank',
    projectName: 'CelemBank',
    category: 'Player',
    command: '.bank balance [player...]',
    aliases: [],
    permission: 'Player; optional target requires admin',
    description: 'Shows the current balance for the sender or, for admins, another player.',
    usage: '.bank balance [player...]',
    examples: ['.bank balance', '.bank balance Luan'],
    language: 'en',
    sourcePath: 'CelemBank/docs/user/commands.md',
    sortOrder: 100,
  },
  {
    id: 'local-celem-logistics-stash',
    projectSlug: 'celem-logistics',
    projectName: 'CelemLogistics',
    category: 'Player',
    command: '.g',
    aliases: ['.guardar'],
    permission: 'Player',
    description: 'Stashes the current inventory immediately.',
    usage: '.g',
    examples: ['.g', '.guardar'],
    language: 'pt-BR',
    sourcePath: 'CelemLogistics/docs/commands.md',
    sortOrder: 380,
  },
  {
    id: 'local-celem-professions-details',
    projectSlug: 'celem-professions',
    projectName: 'CelemProfessions',
    category: 'Player',
    command: '.profession details <profession> [player...]',
    aliases: ['.profession det'],
    permission: 'Player; optional target requires admin',
    description: 'Shows profession level, progress, reset cost, and passive state.',
    usage: '.profession details <profession> [player...]',
    examples: ['.profession details miner'],
    language: 'en',
    sourcePath: 'CelemProfessions/docs/user/commands.md',
    sortOrder: 600,
  },
  {
    id: 'local-celem-store-delete',
    projectSlug: 'celem-store',
    projectName: 'CelemStore',
    category: 'Admin',
    command: '.store delete',
    aliases: [],
    permission: 'Admin',
    description: 'Force-removes the current plot and related shop if present.',
    usage: '.store delete',
    examples: ['.store delete'],
    language: 'en',
    sourcePath: 'CelemStore/docs/user/commands.md',
    sortOrder: 1010,
  },
  {
    id: 'local-celem-zones-create',
    projectSlug: 'celem-zones',
    projectName: 'CelemZones',
    category: 'Admin',
    command: '.zone create <name> <shape> <type> <sizeOrWidth> [height]',
    aliases: [],
    permission: 'Admin',
    description: 'Creates a zone at the sender current position.',
    usage: '.zone create <name> <shape> <type> <sizeOrWidth> [height]',
    examples: ['.zone create arena circle event 20'],
    language: 'en',
    sourcePath: 'CelemZones/docs/user/commands.md',
    sortOrder: 1100,
  },
];
