import { CommandCatalogItem } from '../models/command-catalog.models';

export const LOCAL_COMMAND_CATALOG: CommandCatalogItem[] = [
  {
    id: 'local-celem-bank-balance-player',
    commandKey: 'celem-bank.account.balance',
    projectSlug: 'celem-bank',
    projectName: 'CelemBank',
    category: 'player',
    audience: 'player',
    variantLabel: 'Player',
    isAdminVariant: false,
    command: '.bank balance',
    aliases: [],
    permission: 'Player',
    description: 'Shows the current balance for the sender.',
    usage: '.bank balance',
    examples: ['.bank balance'],
    language: 'english',
    sourcePath: 'CelemBank/docs/user/commands.md',
    sortOrder: 100,
  },
  {
    id: 'local-celem-bank-balance-admin',
    commandKey: 'celem-bank.account.balance',
    projectSlug: 'celem-bank',
    projectName: 'CelemBank',
    category: 'admin',
    audience: 'admin',
    variantLabel: 'Admin',
    isAdminVariant: true,
    command: '.bank balance <player>',
    aliases: [],
    permission: 'Admin',
    description: "Shows another player's current balance for administrators.",
    usage: '.bank balance <player>',
    examples: ['.bank balance Luan'],
    language: 'english',
    sourcePath: 'CelemBank/docs/admin/commands.md',
    sortOrder: 101,
  },
  {
    id: 'local-celem-bank-reload-admin',
    commandKey: 'celem-bank.admin.reload',
    projectSlug: 'celem-bank',
    projectName: 'CelemBank',
    category: 'admin',
    audience: 'admin',
    variantLabel: 'Admin',
    isAdminVariant: true,
    command: '.bank reload',
    aliases: [],
    permission: 'Admin',
    description: 'Reloads CelemBank configuration for administrators.',
    usage: '.bank reload',
    examples: ['.bank reload'],
    language: 'english',
    sourcePath: 'CelemBank/docs/admin/commands.md',
    sortOrder: 102,
  },
  {
    id: 'local-celem-logistics-stash',
    projectSlug: 'celem-logistics',
    projectName: 'CelemLogistics',
    category: 'player',
    audience: 'player',
    variantLabel: 'Player',
    isAdminVariant: false,
    command: '.g',
    aliases: ['.guardar'],
    permission: 'Player',
    description: 'Stashes the current inventory immediately.',
    usage: '.g',
    examples: ['.g', '.guardar'],
    language: 'brazilian',
    sourcePath: 'CelemLogistics/docs/commands.md',
    sortOrder: 380,
  },
  {
    id: 'local-celem-professions-details',
    projectSlug: 'celem-professions',
    projectName: 'CelemProfessions',
    category: 'player',
    audience: 'player',
    variantLabel: 'Player',
    isAdminVariant: false,
    command: '.profession details <profession>',
    aliases: ['.profession det'],
    permission: 'Player',
    description: 'Shows profession level, progress, reset cost, and passive state.',
    usage: '.profession details <profession>',
    examples: ['.profession details miner'],
    language: 'english',
    sourcePath: 'CelemProfessions/docs/user/commands.md',
    sortOrder: 600,
  },
];
