import { CommandCatalogItem } from '../models/command-catalog.models';

export const LOCAL_COMMAND_CATALOG: CommandCatalogItem[] = [
  {
    id: 'local-celem-bank-balance',
    projectSlug: 'celem-bank',
    projectName: 'CelemBank',
    category: 'player',
    command: '.bank balance [player...]',
    aliases: [],
    permission: 'Player; optional target requires admin',
    description: 'Shows the current balance for the sender or, for admins, another player.',
    usage: '.bank balance [player...]',
    examples: ['.bank balance', '.bank balance Luan'],
    language: 'english',
    sourcePath: 'CelemBank/docs/user/commands.md',
    sortOrder: 100,
  },
  {
    id: 'local-celem-logistics-stash',
    projectSlug: 'celem-logistics',
    projectName: 'CelemLogistics',
    category: 'player',
    command: '.g',
    aliases: ['.guardar'],
    permission: 'Player',
    description: 'Stashes the current inventory immediately.',
    usage: '.g',
    examples: ['.g', '.guardar'],
    language: 'brazilian',
    sourcePath: 'CelemLogistics/docs/commands.md',
    sortOrder: 380,
  },
  {
    id: 'local-celem-professions-details',
    projectSlug: 'celem-professions',
    projectName: 'CelemProfessions',
    category: 'player',
    command: '.profession details <profession> [player...]',
    aliases: ['.profession det'],
    permission: 'Player; optional target requires admin',
    description: 'Shows profession level, progress, reset cost, and passive state.',
    usage: '.profession details <profession> [player...]',
    examples: ['.profession details miner'],
    language: 'english',
    sourcePath: 'CelemProfessions/docs/user/commands.md',
    sortOrder: 600,
  },
];
